# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :vmcontainer do |vmcontainer_config|
      vmcontainer_config.vm.box = "ubuntu/xenial64"
      vmcontainer_config.vm.hostname = "vmcontainer"
      vmcontainer_config.vm.network :private_network, ip: "10.0.10.10"
#      vmcontainer_config.vm.provision "file", source: "./examples/id_rsa.pub", destination: ".ssh/authorized_keys"
      vmcontainer_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
#      vmcontainer_config.vm.provision "ansible" do |ansible|
#        ansible.playbook = "vmcontainer_playbook.yml"
#      end
#      graylog_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  config.vm.define :graylog do |graylog_config|
      graylog_config.vm.box = "ubuntu/xenial64"
      graylog_config.vm.hostname = "graylog"
      graylog_config.vm.network :private_network, ip: "10.0.10.20"
#      graylog_config.vm.provision "file", source: "./examples/id_rsa.pub", destination: ".ssh/authorized_keys"
      graylog_config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
#      graylog_config.vm.provision "ansible" do |ansible|
#        ansible.playbook = "graylog_playbook.yml"
#      end
#      graylog_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y python2.7 python-apt
  SHELL

end

